[package]
name = "sci-calc-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.101", features = ["full"] }
quote = "1.0.40"
convert_case = "0.8.0"

[lib]
proc-macro = true
